"""Package-level API tests for pipeline and pipeline.graph."""

import pytest


pytestmark = pytest.mark.package


def test_pipeline_public_exports() -> None:
    import loom.pipeline as pipeline
    import loom.pipeline.graph as graph

    assert pipeline
    assert graph
    assert set(pipeline.__all__) == {
        "OutputSpec",
        "StageFactorySpec",
        "StageSpec",
        "PipelineSpec",
        "parse_pipeline_config",
        "PipelineValidationResult",
        "PipelineTargetCheckResult",
        "validate_pipeline_config",
        "check_pipeline_stage_targets",
        "Stage",
        "StageContext",
        "RunStatus",
        "StageStatus",
        "RunStatusRecord",
        "StageStatusRecord",
        "parse_run_status",
        "parse_stage_status",
        "SubmittedOperationError",
        "SubmittedOperationRecord",
        "SubmittedOperationState",
        "is_active_submitted_operation",
        "is_terminal_submitted_operation",
        "ResourceEntry",
        "ResourceRequest",
        "parse_resource_request",
        "CONTINUE_INDEPENDENT_FAILURE_POLICY",
        "DEFAULT_EXECUTOR_DESCRIPTOR_REGISTRY",
        "DEFAULT_FAILURE_POLICY",
        "DEFAULT_MAX_PARALLEL_STAGES",
        "RUNTIME_CONFIG_SECTION",
        "RUNTIME_METADATA_SCHEMA_VERSION",
        "RUNTIME_PROFILES_CONFIG_SECTION",
        "CapabilityDiagnostic",
        "CapabilitySeverity",
        "CapabilityValidationResult",
        "ExecutionOptions",
        "ExecutorDescriptor",
        "ExecutorDescriptorRegistry",
        "ParallelExecutionOptions",
        "RunEnvironmentRequest",
        "RunOptions",
        "ResolvedStageRuntimeOptions",
        "ResourceCapability",
        "ResourceEnforcementExpectation",
        "ResourceSupportLevel",
        "RuntimeConfigSections",
        "RuntimeMetadata",
        "RuntimeProfile",
        "RuntimeProfileCollection",
        "RuntimeKind",
        "RuntimeRequest",
        "StageEnvironmentRequest",
        "StageRuntimeOptions",
        "build_runtime_metadata",
        "merge_config_run_options",
        "merge_run_options",
        "parallel_execution_options",
        "parse_run_options",
        "parse_runtime_config_sections",
        "parse_runtime_profile",
        "parse_runtime_profiles",
        "parse_runtime_request",
        "resolve_executor_descriptor",
        "resolve_run_runtime",
        "select_runtime_profile",
        "validate_executor_capabilities",
        "validate_stage_runtime_options",
        "PipelineValidationError",
        "PipelineSpecError",
        "RuntimeResourceError",
        "InputBindingError",
        "PipelineGraphError",
        "PipelineCycleError",
        "StageContractError",
        "StatusSerializationError",
        "PipelineRunner",
        "RunRequest",
        "RunResult",
    }

    assert set(graph.__all__) == {
        "ArtifactReference",
        "ResolvedInputBinding",
        "parse_artifact_reference",
        "bind_stage_inputs",
        "resolve_input_bindings",
        "StageEdgeReason",
        "StageNode",
        "StageEdge",
        "StageGraph",
        "build_stage_graph",
        "upstream_of",
        "downstream_of",
        "transitive_upstream",
        "transitive_downstream",
        "detect_cycles",
        "topological_sort",
    }


def test_sweep_package_exports_are_stable() -> None:
    import loom.pipeline.sweep as sweep

    assert set(sweep.__all__) == {
        "SWEEP_DISPATCH_SCHEMA_VERSION",
        "DirectSweepRunResult",
        "DirectSweepTrialResult",
        "QueueSweepDispatchResult",
        "QueueSweepTrialResult",
        "SweepDispatchRequest",
        "SweepDispatchResult",
        "SweepDispatchStatus",
        "SweepQueueDispatchStatus",
        "SweepRunStatus",
        "build_dispatch_requests",
        "build_queue_enqueue_request",
        "build_queue_item_id",
        "build_trial_run_request",
        "enqueue_sweep_trials",
        "run_sweep_direct",
        "SweepCoordinationIdentityResult",
        "SweepCoordinationProjection",
        "SweepTrialCoordinationResult",
        "ensure_sweep_coordination_identity",
        "external_trial_revision",
        "project_sweep_coordination",
        "record_sweep_trial_coordination",
        "trial_state_from_queue_status",
        "trial_state_from_run_status",
        "SWEEP_COLLECTION_SCHEMA_VERSION",
        "SweepCollectedArtifact",
        "SweepCollectedTrial",
        "SweepCollectionDiagnostic",
        "SweepCollectionResult",
        "collect_sweep_results",
        "EARLY_STOP_REASON_CODE",
        "EarlyStopSignal",
        "lifecycle_reason_from_early_stop",
        "stop_early",
        "SWEEP_EXTRACTION_SCHEMA_VERSION",
        "SweepExtractionDiagnostic",
        "SweepExtractionRequest",
        "SweepExtractionResult",
        "SweepExtractionStatus",
        "unsupported_extraction",
        "SWEEP_FEEDBACK_SCHEMA_VERSION",
        "SweepFeedbackObservation",
        "SweepFeedbackStatus",
        "SweepTrialFeedbackRecord",
        "SWEEP_SPEC_SCHEMA_VERSION",
        "DEFAULT_MAX_GENERATED_TRIALS",
        "SweepMode",
        "GridSweepSpec",
        "ManualSweepSpec",
        "ManualTrialSpec",
        "parse_sweep_spec",
        "sweep_spec_to_dict",
        "GridSweepProposalProvider",
        "ManualSweepProposalProvider",
        "AUTHORED_SWEEP_SPEC_FILE_NAME",
        "SweepPlan",
        "SweepPlanPaths",
        "SweepPlanCompatibilityResult",
        "provider_for_spec",
        "plan_sweep",
        "plan_sweep_from_file",
        "write_sweep_plan",
        "read_sweep_plan",
        "check_existing_sweep_plan",
        "build_trial_id",
        "build_trial_run_uri",
        "trial_override_expressions",
        "SweepAggregateStatus",
        "SweepStatusSummary",
        "SweepTrialOutcome",
        "SweepTrialStatus",
        "build_sweep_status",
        "SWEEP_MANIFEST_SCHEMA_VERSION",
        "TRIALS_MANIFEST_SCHEMA_VERSION",
        "SWEEP_MANIFEST_FILE_NAME",
        "TRIALS_MANIFEST_FILE_NAME",
        "SweepManifest",
        "TrialsManifest",
        "SweepManifestCompatibilityDiagnostic",
        "check_sweep_manifest_payload",
        "check_trials_manifest_payload",
        "read_sweep_manifest",
        "read_trials_manifest",
        "write_sweep_manifest",
        "write_trials_manifest",
        "SweepProviderIdentity",
        "SweepProviderContext",
        "SweepProposalProvider",
        "FiniteSweepProposalProvider",
        "TrialProposal",
        "provider_is_finite",
        "provider_trial_count",
        "SweepTrialRecord",
        "SweepError",
        "SweepExtractionError",
        "SweepManifestError",
        "SweepProtocolError",
    }


def test_pipeline_imports_are_explicit() -> None:
    import loom as loom_package
    import loom.pipeline as pipeline
    import loom.pipeline.graph as graph

    assert "pipeline" not in loom_package.__all__
    assert pipeline
    assert graph
