"""Pipeline execution API."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from loom.pipeline.execution.errors import (
        LifecycleError,
        OutputValidationError,
        ParallelExecutionUnsupportedError,
        PipelineExecutionError,
        PlanExecutionError,
        RunRequestError,
        StageExecutionRuntimeError,
    )
    from loom.pipeline.execution.continuation import (
        ContinuationStateError,
        InsufficientPreparedStateError,
        PreparedRunContinueRequest,
        PreparedRunContinueResult,
        StageJobRunRequest,
        StageJobRunResult,
        UnsupportedContinuationExecutorError,
        continue_prepared_run,
        run_stage_job,
        validate_prepared_run_plugin_activations,
    )
    from loom.pipeline.execution.models import (
        ConfigSnapshotInputs,
        ExecutionFailure,
        FailurePolicy,
        RunRequest,
        RunResult,
        StageExecutionRequest,
        StageExecutionResult,
        StageRunResult,
        StageWorkerRequest,
        StageWorkerResult,
    )
    from loom.pipeline.execution.prepared_run import (
        PREPARED_RUN_CONTINUATION_WHOLE_RUN,
        PREPARED_RUN_SCHEMA_VERSION,
        PreparedRunPayloadError,
        PreparedRunRecord,
    )
    from loom.pipeline.execution.models import redact_executor_metadata
    from loom.pipeline.execution.outputs import validate_stage_outputs
    from loom.pipeline.execution.offline_adapter import (
        OfflineEvidenceRunStore,
        create_offline_evidence_run_store,
        is_offline_evidence_run_store,
    )
    from loom.pipeline.execution.runner import PipelineRunner, run_pipeline
    from loom.pipeline.execution.services import RuntimeServices
    from loom.pipeline.execution.resource_admission import (
        ResourceAdmissionDecision,
        ResourceAdmissionError,
        ResourceAdmissionRequest,
        ResourceAdmissionStatus,
        ResourceLimitReconciliationResult,
        ResourceLimitReconciliationStatus,
        ResourceLeaseRequest,
        acquire_resource_admission,
        reconcile_resource_limits,
        release_resource_admission,
        resource_requests_from_runtime,
    )
    from loom.pipeline.execution.authority_adapter import (
        create_authority_backed_serial_run_store,
    )
    from loom.pipeline.execution.stage_attempts import prepare_stage_attempt
    from loom.pipeline.execution.stage_worker import (
        StageWorkerRunRequest,
        StageWorkerStateError,
        infer_stage_worker_attempt,
        reconstruct_stage_execution_request,
        run_stage_worker,
        validate_stage_worker_plugin_activations,
    )


def __getattr__(name: str) -> object:
    if name in {
        "ConfigSnapshotInputs",
        "ContinuationStateError",
        "ExecutionFailure",
        "FailurePolicy",
        "InsufficientPreparedStateError",
        "LifecycleError",
        "OutputValidationError",
        "OfflineEvidenceRunStore",
        "ParallelExecutionUnsupportedError",
        "PipelineExecutionError",
        "PipelineRunner",
        "PlanExecutionError",
        "PREPARED_RUN_CONTINUATION_WHOLE_RUN",
        "PREPARED_RUN_SCHEMA_VERSION",
        "PreparedRunPayloadError",
        "PreparedRunRecord",
        "PreparedRunContinueRequest",
        "PreparedRunContinueResult",
        "RunRequest",
        "RunRequestError",
        "RunResult",
        "RuntimeServices",
        "ResourceAdmissionDecision",
        "ResourceAdmissionError",
        "ResourceAdmissionRequest",
        "ResourceAdmissionStatus",
        "ResourceLimitReconciliationResult",
        "ResourceLimitReconciliationStatus",
        "ResourceLeaseRequest",
        "StageExecutionRequest",
        "StageExecutionResult",
        "StageExecutionRuntimeError",
        "StageJobRunRequest",
        "StageJobRunResult",
        "StageRunResult",
        "StageWorkerRunRequest",
        "StageWorkerRequest",
        "StageWorkerResult",
        "StageWorkerStateError",
        "UnsupportedContinuationExecutorError",
        "continue_prepared_run",
        "create_authority_backed_serial_run_store",
        "create_offline_evidence_run_store",
        "acquire_resource_admission",
        "infer_stage_worker_attempt",
        "is_offline_evidence_run_store",
        "prepare_stage_attempt",
        "reconcile_resource_limits",
        "reconstruct_stage_execution_request",
        "redact_executor_metadata",
        "release_resource_admission",
        "resource_requests_from_runtime",
        "run_stage_worker",
        "validate_stage_worker_plugin_activations",
        "run_stage_job",
        "run_pipeline",
        "validate_stage_outputs",
        "validate_prepared_run_plugin_activations",
    }:
        from loom.pipeline.execution.continuation import (
            ContinuationStateError,
            InsufficientPreparedStateError,
            PreparedRunContinueRequest,
            PreparedRunContinueResult,
            StageJobRunRequest,
            StageJobRunResult,
            UnsupportedContinuationExecutorError,
            continue_prepared_run,
            run_stage_job,
            validate_prepared_run_plugin_activations,
        )
        from loom.pipeline.execution.errors import (
            LifecycleError,
            OutputValidationError,
            ParallelExecutionUnsupportedError,
            PipelineExecutionError,
            PlanExecutionError,
            RunRequestError,
            StageExecutionRuntimeError,
        )
        from loom.pipeline.execution.models import (
            ConfigSnapshotInputs,
            ExecutionFailure,
            FailurePolicy,
            RunRequest,
            RunResult,
            StageExecutionRequest,
            StageExecutionResult,
            StageRunResult,
            StageWorkerRequest,
            StageWorkerResult,
            redact_executor_metadata,
        )
        from loom.pipeline.execution.outputs import validate_stage_outputs
        from loom.pipeline.execution.offline_adapter import (
            OfflineEvidenceRunStore,
            create_offline_evidence_run_store,
            is_offline_evidence_run_store,
        )
        from loom.pipeline.execution.prepared_run import (
            PREPARED_RUN_CONTINUATION_WHOLE_RUN,
            PREPARED_RUN_SCHEMA_VERSION,
            PreparedRunPayloadError,
            PreparedRunRecord,
        )
        from loom.pipeline.execution.runner import PipelineRunner, run_pipeline
        from loom.pipeline.execution.services import RuntimeServices
        from loom.pipeline.execution.resource_admission import (
            ResourceAdmissionDecision,
            ResourceAdmissionError,
            ResourceAdmissionRequest,
            ResourceAdmissionStatus,
            ResourceLimitReconciliationResult,
            ResourceLimitReconciliationStatus,
            ResourceLeaseRequest,
            acquire_resource_admission,
            reconcile_resource_limits,
            release_resource_admission,
            resource_requests_from_runtime,
        )
        from loom.pipeline.execution.authority_adapter import (
            create_authority_backed_serial_run_store,
        )
        from loom.pipeline.execution.stage_attempts import prepare_stage_attempt
        from loom.pipeline.execution.stage_worker import (
            StageWorkerRunRequest,
            StageWorkerStateError,
            infer_stage_worker_attempt,
            reconstruct_stage_execution_request,
            run_stage_worker,
            validate_stage_worker_plugin_activations,
        )

        return {
            "ConfigSnapshotInputs": ConfigSnapshotInputs,
            "ContinuationStateError": ContinuationStateError,
            "ExecutionFailure": ExecutionFailure,
            "FailurePolicy": FailurePolicy,
            "InsufficientPreparedStateError": InsufficientPreparedStateError,
            "LifecycleError": LifecycleError,
            "OutputValidationError": OutputValidationError,
            "OfflineEvidenceRunStore": OfflineEvidenceRunStore,
            "ParallelExecutionUnsupportedError": ParallelExecutionUnsupportedError,
            "PipelineExecutionError": PipelineExecutionError,
            "PipelineRunner": PipelineRunner,
            "PlanExecutionError": PlanExecutionError,
            "PREPARED_RUN_CONTINUATION_WHOLE_RUN": PREPARED_RUN_CONTINUATION_WHOLE_RUN,
            "PREPARED_RUN_SCHEMA_VERSION": PREPARED_RUN_SCHEMA_VERSION,
            "PreparedRunPayloadError": PreparedRunPayloadError,
            "PreparedRunRecord": PreparedRunRecord,
            "PreparedRunContinueRequest": PreparedRunContinueRequest,
            "PreparedRunContinueResult": PreparedRunContinueResult,
            "RunRequest": RunRequest,
            "RunRequestError": RunRequestError,
            "RunResult": RunResult,
            "RuntimeServices": RuntimeServices,
            "ResourceAdmissionDecision": ResourceAdmissionDecision,
            "ResourceAdmissionError": ResourceAdmissionError,
            "ResourceAdmissionRequest": ResourceAdmissionRequest,
            "ResourceAdmissionStatus": ResourceAdmissionStatus,
            "ResourceLimitReconciliationResult": ResourceLimitReconciliationResult,
            "ResourceLimitReconciliationStatus": ResourceLimitReconciliationStatus,
            "ResourceLeaseRequest": ResourceLeaseRequest,
            "StageExecutionRequest": StageExecutionRequest,
            "StageExecutionResult": StageExecutionResult,
            "StageExecutionRuntimeError": StageExecutionRuntimeError,
            "StageJobRunRequest": StageJobRunRequest,
            "StageJobRunResult": StageJobRunResult,
            "StageRunResult": StageRunResult,
            "StageWorkerRunRequest": StageWorkerRunRequest,
            "StageWorkerRequest": StageWorkerRequest,
            "StageWorkerResult": StageWorkerResult,
            "StageWorkerStateError": StageWorkerStateError,
            "UnsupportedContinuationExecutorError": UnsupportedContinuationExecutorError,
            "continue_prepared_run": continue_prepared_run,
            "create_authority_backed_serial_run_store": (
                create_authority_backed_serial_run_store
            ),
            "create_offline_evidence_run_store": create_offline_evidence_run_store,
            "acquire_resource_admission": acquire_resource_admission,
            "infer_stage_worker_attempt": infer_stage_worker_attempt,
            "is_offline_evidence_run_store": is_offline_evidence_run_store,
            "prepare_stage_attempt": prepare_stage_attempt,
            "reconcile_resource_limits": reconcile_resource_limits,
            "reconstruct_stage_execution_request": reconstruct_stage_execution_request,
            "redact_executor_metadata": redact_executor_metadata,
            "release_resource_admission": release_resource_admission,
            "resource_requests_from_runtime": resource_requests_from_runtime,
            "run_stage_worker": run_stage_worker,
            "validate_stage_worker_plugin_activations": (
                validate_stage_worker_plugin_activations
            ),
            "run_stage_job": run_stage_job,
            "run_pipeline": run_pipeline,
            "validate_stage_outputs": validate_stage_outputs,
            "validate_prepared_run_plugin_activations": (
                validate_prepared_run_plugin_activations
            ),
        }[name]
    raise AttributeError(f"module 'loom.pipeline.execution' has no attribute {name!r}")


__all__ = [
    "ConfigSnapshotInputs",
    "ContinuationStateError",
    "ExecutionFailure",
    "FailurePolicy",
    "InsufficientPreparedStateError",
    "LifecycleError",
    "OutputValidationError",
    "OfflineEvidenceRunStore",
    "ParallelExecutionUnsupportedError",
    "PipelineExecutionError",
    "PipelineRunner",
    "PlanExecutionError",
    "PREPARED_RUN_CONTINUATION_WHOLE_RUN",
    "PREPARED_RUN_SCHEMA_VERSION",
    "PreparedRunPayloadError",
    "PreparedRunRecord",
    "PreparedRunContinueRequest",
    "PreparedRunContinueResult",
    "RunRequest",
    "RunRequestError",
    "RunResult",
    "RuntimeServices",
    "ResourceAdmissionDecision",
    "ResourceAdmissionError",
    "ResourceAdmissionRequest",
    "ResourceAdmissionStatus",
    "ResourceLimitReconciliationResult",
    "ResourceLimitReconciliationStatus",
    "ResourceLeaseRequest",
    "StageExecutionRequest",
    "StageExecutionResult",
    "StageExecutionRuntimeError",
    "StageJobRunRequest",
    "StageJobRunResult",
    "StageRunResult",
    "StageWorkerRunRequest",
    "StageWorkerRequest",
    "StageWorkerResult",
    "StageWorkerStateError",
    "UnsupportedContinuationExecutorError",
    "acquire_resource_admission",
    "continue_prepared_run",
    "create_authority_backed_serial_run_store",
    "create_offline_evidence_run_store",
    "infer_stage_worker_attempt",
    "is_offline_evidence_run_store",
    "prepare_stage_attempt",
    "reconcile_resource_limits",
    "reconstruct_stage_execution_request",
    "redact_executor_metadata",
    "release_resource_admission",
    "resource_requests_from_runtime",
    "run_stage_worker",
    "validate_stage_worker_plugin_activations",
    "run_stage_job",
    "run_pipeline",
    "validate_stage_outputs",
    "validate_prepared_run_plugin_activations",
]
