"""Deterministic sweep contracts and persisted manifest records."""

from .dispatch import (
    SWEEP_DISPATCH_SCHEMA_VERSION,
    DirectSweepRunResult,
    DirectSweepTrialResult,
    SweepDispatchRequest,
    SweepDispatchResult,
    SweepDispatchStatus,
    SweepRunStatus,
    build_dispatch_requests,
    build_trial_run_request,
    run_sweep_direct,
)
from .early_stopping import (
    EARLY_STOP_REASON_CODE,
    EarlyStopSignal,
    lifecycle_reason_from_early_stop,
    stop_early,
)
from .errors import (
    SweepError,
    SweepExtractionError,
    SweepManifestError,
    SweepProtocolError,
)
from .extraction import (
    SWEEP_EXTRACTION_SCHEMA_VERSION,
    SweepExtractionDiagnostic,
    SweepExtractionRequest,
    SweepExtractionResult,
    SweepExtractionStatus,
    unsupported_extraction,
)
from .feedback import (
    SWEEP_FEEDBACK_SCHEMA_VERSION,
    SweepFeedbackObservation,
    SweepFeedbackStatus,
    SweepTrialFeedbackRecord,
)
from .grid import GridSweepProposalProvider
from .manifest import (
    SWEEP_MANIFEST_FILE_NAME,
    SWEEP_MANIFEST_SCHEMA_VERSION,
    TRIALS_MANIFEST_FILE_NAME,
    TRIALS_MANIFEST_SCHEMA_VERSION,
    SweepManifest,
    SweepManifestCompatibilityDiagnostic,
    TrialsManifest,
    check_sweep_manifest_payload,
    check_trials_manifest_payload,
    read_sweep_manifest,
    read_trials_manifest,
    write_sweep_manifest,
    write_trials_manifest,
)
from .manual import ManualSweepProposalProvider
from .providers import (
    FiniteSweepProposalProvider,
    SweepProviderContext,
    SweepProviderIdentity,
    SweepProposalProvider,
    TrialProposal,
    provider_is_finite,
    provider_trial_count,
)
from .runner import (
    AUTHORED_SWEEP_SPEC_FILE_NAME,
    SweepPlan,
    SweepPlanCompatibilityResult,
    SweepPlanPaths,
    build_trial_id,
    build_trial_run_uri,
    check_existing_sweep_plan,
    plan_sweep,
    plan_sweep_from_file,
    provider_for_spec,
    read_sweep_plan,
    trial_override_expressions,
    write_sweep_plan,
)
from .spec import (
    DEFAULT_MAX_GENERATED_TRIALS,
    SWEEP_SPEC_SCHEMA_VERSION,
    GridSweepSpec,
    ManualSweepSpec,
    ManualTrialSpec,
    SweepMode,
    parse_sweep_spec,
    sweep_spec_to_dict,
)
from .trials import SweepTrialRecord

__all__ = [
    "SWEEP_DISPATCH_SCHEMA_VERSION",
    "DirectSweepRunResult",
    "DirectSweepTrialResult",
    "SweepDispatchRequest",
    "SweepDispatchResult",
    "SweepDispatchStatus",
    "SweepRunStatus",
    "build_dispatch_requests",
    "build_trial_run_request",
    "run_sweep_direct",
    "EARLY_STOP_REASON_CODE",
    "EarlyStopSignal",
    "lifecycle_reason_from_early_stop",
    "stop_early",
    "SWEEP_EXTRACTION_SCHEMA_VERSION",
    "SweepExtractionDiagnostic",
    "SweepExtractionRequest",
    "SweepExtractionResult",
    "SweepExtractionStatus",
    "unsupported_extraction",
    "SWEEP_FEEDBACK_SCHEMA_VERSION",
    "SweepFeedbackObservation",
    "SweepFeedbackStatus",
    "SweepTrialFeedbackRecord",
    "SWEEP_SPEC_SCHEMA_VERSION",
    "DEFAULT_MAX_GENERATED_TRIALS",
    "SweepMode",
    "GridSweepSpec",
    "ManualSweepSpec",
    "ManualTrialSpec",
    "parse_sweep_spec",
    "sweep_spec_to_dict",
    "GridSweepProposalProvider",
    "ManualSweepProposalProvider",
    "AUTHORED_SWEEP_SPEC_FILE_NAME",
    "SweepPlan",
    "SweepPlanPaths",
    "SweepPlanCompatibilityResult",
    "provider_for_spec",
    "plan_sweep",
    "plan_sweep_from_file",
    "write_sweep_plan",
    "read_sweep_plan",
    "check_existing_sweep_plan",
    "build_trial_id",
    "build_trial_run_uri",
    "trial_override_expressions",
    "SWEEP_MANIFEST_SCHEMA_VERSION",
    "TRIALS_MANIFEST_SCHEMA_VERSION",
    "SWEEP_MANIFEST_FILE_NAME",
    "TRIALS_MANIFEST_FILE_NAME",
    "SweepManifest",
    "TrialsManifest",
    "SweepManifestCompatibilityDiagnostic",
    "check_sweep_manifest_payload",
    "check_trials_manifest_payload",
    "read_sweep_manifest",
    "read_trials_manifest",
    "write_sweep_manifest",
    "write_trials_manifest",
    "SweepProviderIdentity",
    "SweepProviderContext",
    "SweepProposalProvider",
    "FiniteSweepProposalProvider",
    "TrialProposal",
    "provider_is_finite",
    "provider_trial_count",
    "SweepTrialRecord",
    "SweepError",
    "SweepExtractionError",
    "SweepManifestError",
    "SweepProtocolError",
]
