"""Pure SLURM dry-run planning contracts."""

from __future__ import annotations
from .errors import (
    SlurmActiveSubmissionError,
    SlurmCapabilityUnavailableError,
    SlurmCommandExecutionError,
    SlurmCommandUnavailableError,
    SlurmJobIdParseError,
    SlurmLiveOperationError,
    SlurmManifestError,
    SlurmManifestUpdateError,
    SlurmOptionError,
    SlurmPathError,
    SlurmPlanningError,
    SlurmResourceMappingError,
    SlurmSubmissionError,
)
from .commands import (
    MAX_PERSISTED_COMMAND_OUTPUT_CHARS,
    SLURM_COMMAND_RESULT_SCHEMA_VERSION,
    FakeSlurmCommandRunner,
    SlurmCommandResult,
    SlurmCommandRunner,
    SlurmParsedJobId,
    SubprocessSlurmCommandRunner,
    bound_scheduler_output,
    command_result_from_exception,
    parse_sbatch_parsable_output,
)
from .container import (
    wrap_slurm_command_with_apptainer,
)
from .manifest import (
    SLURM_PLANNED_SUBMISSION_SCHEMA_VERSION,
    SlurmDependencyType,
    SlurmMode,
    SlurmPlannedDependency,
    SlurmPlannedJob,
    SlurmPlannedSubmission,
    pipeline_job_key,
    stage_job_key,
    validate_logical_job_key,
)
from .live import (
    SLURM_LIVE_SUBMISSION_SCHEMA_VERSION,
    SlurmCancellationAttempt,
    SlurmFailedSubmission,
    SlurmLiveSubmissionManifest,
    SlurmLiveSubmissionStatus,
    SlurmSchedulerOperation,
    SlurmSchedulerOperationState,
    SlurmSchedulerStatusSnapshot,
    SlurmSubmittedJob,
    live_manifest_from_planned_submission,
    read_slurm_live_manifest,
    write_slurm_live_manifest,
)
from .options import (
    DEFAULT_SLURM_LAUNCHER_ARGV,
    GENERATED_SBATCH_DIRECTIVES,
    MODELED_SBATCH_DIRECTIVES,
    RESERVED_SBATCH_DIRECTIVES,
    SLURM_OPTIONS_SCHEMA_VERSION,
    SlurmCommandArgv,
    SlurmOptions,
    normalize_extra_sbatch,
)
from .paths import (
    SLURM_SUBMISSION_ROOT,
    SlurmGeneratedArtifactPath,
    resolve_slurm_generated_artifact_path,
    resolve_slurm_manifest_path,
    slurm_job_log_relative_path,
    slurm_job_script_relative_path,
    slurm_manifest_relative_path,
    slurm_plan_relative_path,
    slurm_submission_relative_path,
)
from .rendering import render_command_argv, render_sbatch_directive
from .ready_stage import SlurmReadyStageProfile
from .resources import (
    SlurmSbatchDirective,
    build_sbatch_directives,
    map_slurm_resources,
)

__all__ = [
    "DEFAULT_SLURM_LAUNCHER_ARGV",
    "GENERATED_SBATCH_DIRECTIVES",
    "MAX_PERSISTED_COMMAND_OUTPUT_CHARS",
    "MODELED_SBATCH_DIRECTIVES",
    "RESERVED_SBATCH_DIRECTIVES",
    "SLURM_COMMAND_RESULT_SCHEMA_VERSION",
    "SLURM_LIVE_SUBMISSION_SCHEMA_VERSION",
    "SLURM_OPTIONS_SCHEMA_VERSION",
    "SLURM_PLANNED_SUBMISSION_SCHEMA_VERSION",
    "SLURM_SUBMISSION_ROOT",
    "FakeSlurmCommandRunner",
    "SlurmActiveSubmissionError",
    "SlurmCancellationAttempt",
    "SlurmCapabilityUnavailableError",
    "SlurmCommandArgv",
    "SlurmCommandExecutionError",
    "SlurmCommandResult",
    "SlurmCommandRunner",
    "SlurmCommandUnavailableError",
    "SlurmDependencyType",
    "SlurmFailedSubmission",
    "SlurmGeneratedArtifactPath",
    "SlurmJobIdParseError",
    "SlurmLiveOperationError",
    "SlurmLiveSubmissionManifest",
    "SlurmLiveSubmissionStatus",
    "SlurmManifestError",
    "SlurmManifestUpdateError",
    "SlurmMode",
    "SlurmOptionError",
    "SlurmOptions",
    "SlurmPathError",
    "SlurmParsedJobId",
    "SlurmPlannedDependency",
    "SlurmPlannedJob",
    "SlurmPlannedSubmission",
    "SlurmPlanningError",
    "SlurmResourceMappingError",
    "SlurmReadyStageProfile",
    "SlurmSbatchDirective",
    "SlurmSchedulerOperation",
    "SlurmSchedulerOperationState",
    "SlurmSchedulerStatusSnapshot",
    "SlurmSubmittedJob",
    "SlurmSubmissionError",
    "SubprocessSlurmCommandRunner",
    "bound_scheduler_output",
    "build_sbatch_directives",
    "command_result_from_exception",
    "live_manifest_from_planned_submission",
    "map_slurm_resources",
    "normalize_extra_sbatch",
    "pipeline_job_key",
    "parse_sbatch_parsable_output",
    "read_slurm_live_manifest",
    "render_command_argv",
    "render_sbatch_directive",
    "resolve_slurm_generated_artifact_path",
    "resolve_slurm_manifest_path",
    "slurm_job_log_relative_path",
    "slurm_job_script_relative_path",
    "slurm_manifest_relative_path",
    "slurm_plan_relative_path",
    "slurm_submission_relative_path",
    "stage_job_key",
    "validate_logical_job_key",
    "wrap_slurm_command_with_apptainer",
    "write_slurm_live_manifest",
]
