"""Tests for store error exports and inheritance."""

import loom.pipeline.stores as stores


def test_store_error_inheritance() -> None:
    assert issubclass(stores.StoreError, Exception)
    assert issubclass(stores.ArtifactStoreError, stores.StoreError)
    assert issubclass(stores.RunStoreError, stores.StoreError)
    assert issubclass(stores.PreparedRunStorePayloadError, stores.RunStoreError)
    assert issubclass(stores.UnsafeStorePathError, stores.StoreError)
    assert issubclass(stores.InvalidRunURIError, stores.RunStoreError)
    assert issubclass(stores.UnsupportedArtifactURIError, stores.ArtifactStoreError)
    assert issubclass(stores.ArtifactNotFoundError, stores.ArtifactStoreError)
    assert issubclass(stores.MissingArtifactCodecError, stores.ArtifactStoreError)
    assert issubclass(stores.ArtifactTypeMismatchError, stores.ArtifactStoreError)
    assert issubclass(stores.ArtifactChecksumMismatchError, stores.ArtifactStoreError)
    assert issubclass(
        stores.ArtifactChecksumUnsupportedError, stores.ArtifactStoreError
    )
    assert issubclass(stores.AtomicWriteError, stores.StoreError)
    assert issubclass(stores.RunAlreadyExistsError, stores.RunStoreError)
    assert issubclass(stores.RunLockError, stores.RunStoreError)
    assert issubclass(stores.RunLockConflictError, stores.RunLockError)
    assert issubclass(stores.RunLockReleaseError, stores.RunLockError)
    assert issubclass(stores.RunNotFoundError, stores.RunStoreError)
    assert issubclass(stores.MissingStoreDocumentError, stores.RunStoreError)
    assert issubclass(stores.CorruptStoreDocumentError, stores.RunStoreError)
    assert issubclass(stores.StageStateNotFoundError, stores.RunStoreError)


def test_store_error_exports() -> None:
    assert stores.__all__ == [
        "ArtifactStore",
        "RunArtifactStore",
        "StageArtifactStore",
        "LocalArtifactStore",
        "LocalRunArtifactStore",
        "LocalStageArtifactStore",
        "PerRunAuthorityStore",
        "RunStore",
        "StageStore",
        "AuthorityStoreError",
        "StatusTransition",
        "AttemptAllocation",
        "OutputCommit",
        "AUTHORITY_MUTATION_ROUTE_PREFIX",
        "AUTHORITY_MUTATION_RUN_ADMIT_PATH",
        "AUTHORITY_MUTATION_OPEN_RUN_PATH",
        "AUTHORITY_MUTATION_RUN_TRANSITION_PATH",
        "AUTHORITY_MUTATION_STAGE_TRANSITION_PATH",
        "AUTHORITY_MUTATION_ALLOCATE_STAGE_ATTEMPT_PATH",
        "AUTHORITY_MUTATION_RECORD_OUTPUT_COMMIT_PATH",
        "AuthorityClient",
        "AuthorityClientError",
        "DEFAULT_AUTHORITY_READINESS_TIMEOUT_SECONDS",
        "AuthorityFactoryError",
        "AuthorityFactoryResolution",
        "config_from_authority_reference",
        "create_authority_client",
        "probe_http_authority_readiness",
        "require_online_authority",
        "resolve_authority_for_factory",
        "AUTHORITY_REGISTRY_ALLOCATIONS_DIR",
        "AUTHORITY_REGISTRY_CURRENT_FILE",
        "AUTHORITY_REGISTRY_DIR",
        "AUTHORITY_REGISTRY_SCHEMA_VERSION",
        "AuthorityRegistryAllocationScope",
        "AuthorityRegistryError",
        "AuthorityRegistryRecord",
        "AuthorityRegistryValidationResult",
        "AuthorityRegistryValidationStatus",
        "authority_registry_dir",
        "authority_registry_hint_from_record",
        "authority_registry_record_path",
        "authority_service_health_from_record",
        "read_authority_registry_record",
        "validate_authority_registry",
        "validate_authority_registry_record",
        "write_authority_registry_record",
        "BackendCapability",
        "CapabilityScope",
        "CapabilitySupport",
        "DiagnosticSeverity",
        "UnsupportedCapabilityCode",
        "BackendCapabilityRecord",
        "BackendCapabilitySet",
        "UnsupportedCapability",
        "StoreDiagnostic",
        "AuthorityCapabilityError",
        "LOOM_AUTHORITY_MODE",
        "AuthorityResolutionError",
        "AuthorityResolutionMode",
        "AuthorityReferenceSource",
        "AuthorityServiceHealthState",
        "AuthorityResolutionOutcomeKind",
        "AuthorityResolutionFailureKind",
        "AuthorityResolutionDiagnosticSeverity",
        "AuthorityResolverDiagnostic",
        "AuthorityRegistryHint",
        "AuthorityServiceHealth",
        "AuthorityResolverInput",
        "AuthorityResolutionResult",
        "resolve_authority",
        "authority_resolution_mode_from_env",
        "authority_resolution_mode_from_mapping",
        "authority_resolution_mode_to_env",
        "AUTHORITY_PROTOCOL_VERSION",
        "AuthorityProtocolError",
        "AuthorityProtocolOperationKind",
        "AuthorityProtocolErrorCategory",
        "AuthorityReadinessState",
        "AuthorityProtocolVersion",
        "AuthorityProtocolMetadata",
        "AuthorityProtocolRequest",
        "AuthorityProtocolReadiness",
        "AuthorityProtocolResult",
        "AuthorityProtocolRejection",
        "AuthorityProtocolResponse",
        "accepted_authority_response",
        "rejected_authority_response",
        "protocol_versions_compatible",
        "AuthorityBackendKind",
        "AuthorityDeploymentProfile",
        "AuthorityReference",
        "AuthorityConfig",
        "AuthorityConfigError",
        "authority_config_from_env",
        "authority_config_from_mapping",
        "authority_config_to_cli_args",
        "authority_config_to_env",
        "default_deployment_profile_for_backend",
        "RequiredAuthorityCapability",
        "CapabilityAdmissionResult",
        "CapabilityAdmissionError",
        "AuthorityAdmissionError",
        "admit_authority_capabilities",
        "create_run_store",
        "AUTHORITY_SCHEMA_VERSION",
        "AuthoritySchemaError",
        "AuthoritySchemaFailureKind",
        "AuthoritySchemaFailure",
        "AuthoritySchemaCheck",
        "check_authority_schema_version",
        "AuthorityModelError",
        "LeaseKind",
        "LeaseState",
        "MaterializedRefKind",
        "CleanupCandidateKind",
        "RecoveryKind",
        "StaticOutcomeKind",
        "ReadModelWarningCode",
        "BackendRevision",
        "LifecycleReason",
        "StageAttempt",
        "LeaseRecord",
        "OutputCommitRecord",
        "ArtifactFactRecord",
        "MaterializedRef",
        "CleanupCandidate",
        "RecoveryRecord",
        "StaticOutcomeRecord",
        "ReadModelWarning",
        "StageLifecycleSnapshot",
        "AuthoritativeRunSnapshot",
        "WorkspaceCoordinationStore",
        "CoordinationStoreError",
        "TrialState",
        "WorkspaceIdentity",
        "SweepIdentity",
        "TrialReference",
        "TrialLeaseRecord",
        "ResourceLeaseRecord",
        "CoordinationRecoveryRecord",
        "ConcurrencyCounter",
        "coordination_requirement_diagnostics",
        "AuthorityDeploymentError",
        "AuthorityDeploymentPreflightResult",
        "AuthorityDeploymentProfileSummary",
        "describe_authority_deployment",
        "preflight_authority_deployment",
        "DEFERRED_RESULT_ENVELOPE_SCHEMA_VERSION",
        "DeferredFinalizationError",
        "DeferredReconciliationCode",
        "DeferredReconciliationResult",
        "DeferredResultEnvelope",
        "reconcile_deferred_result",
        "LegacyRunStore",
        "RunLifecycleStore",
        "RunDocumentStore",
        "RunFreshnessStore",
        "RunFreshnessRecord",
        "RunFreshnessError",
        "RunEventStore",
        "RunInspectionStore",
        "RunLockStore",
        "RunStatusStore",
        "RunPlanStore",
        "RunPreparedRunStore",
        "RunArtifactIndexStore",
        "RunConfigStore",
        "RunProvenanceStore",
        "RunRuntimeMetadataStore",
        "RunSubmittedOperationStore",
        "StageStateStore",
        "StageLogStore",
        "StageWorkspaceStore",
        "LocalRunStorePaths",
        "LocalRunStore",
        "RunStageInspection",
        "RunStateInspection",
        "AuthoritativeReadOptions",
        "CompletedRunBundleMetadata",
        "LocalMaterializationRequest",
        "MaterializationReadModelError",
        "artifact_payload_ref",
        "collect_local_materialized_refs",
        "read_authoritative_run",
        "read_completed_run_bundle_metadata",
        "StoreError",
        "ArtifactStoreError",
        "RunStoreError",
        "PreparedRunStorePayloadError",
        "RunLockError",
        "RunLockConflictError",
        "RunLockReleaseError",
        "UnsafeStorePathError",
        "InvalidRunURIError",
        "UnsupportedArtifactURIError",
        "ArtifactNotFoundError",
        "MissingArtifactCodecError",
        "ArtifactTypeMismatchError",
        "ArtifactChecksumMismatchError",
        "ArtifactChecksumUnsupportedError",
        "RunAlreadyExistsError",
        "RunNotFoundError",
        "MissingStoreDocumentError",
        "CorruptStoreDocumentError",
        "StageStateNotFoundError",
        "AtomicWriteError",
        "ensure_dir",
        "unique_temp_path",
        "atomic_write_bytes",
        "atomic_write_text",
        "atomic_write_json",
        "replace_file",
        "format_artifact_key",
        "parse_artifact_key",
        "artifact_index_to_dict",
        "artifact_index_from_dict",
        "merge_artifact_index",
        "LocalRunURI",
        "resolve_local_run_uri",
        "validate_run_uri",
        "run_uri_to_path",
        "path_to_run_uri",
        "allocate_local_run_uri",
    ]
